### ISSUE TITLE
Exception ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by vzool** [alhazmy13/HijriDatePicker#26]
Hi, I have an issue here:
```
09-27 10:56:03.189 E/ACRA    (16515): ACRA caught a ArrayIndexOutOfBoundsException for com.example.app
09-27 10:56:03.189 E/ACRA    (16515): java.lang.ArrayIndexOutOfBoundsException: length=1741; index=-1
09-27 10:56:03.189 E/ACRA    (16515): 	at com.github.msarhan.ummalqura.calendar.UmmalquraGregorianConverter.d2h(UmmalquraGregorianConverter.java:75)
09-27 10:56:03.189 E/ACRA    (16515): 	at com.github.msarhan.ummalqura.calendar.UmmalquraGregorianConverter.toHijri(UmmalquraGregorianConverter.java:24)
09-27 10:56:03.189 E/ACRA    (16515): 	at com.github.msarhan.ummalqura.calendar.UmmalquraGregorianConverter.toHijri(UmmalquraGregorianConverter.java:17)
09-27 10:56:03.189 E/ACRA    (16515): 	at com.github.msarhan.ummalqura.calendar.UmmalquraCalendar.computeFields(UmmalquraCalendar.java:444)
09-27 10:56:03.189 E/ACRA    (16515): 	at java.util.Calendar.setTimeInMillis(Calendar.java:1122)
09-27 10:56:03.189 E/ACRA    (16515): 	at java.util.Calendar.setTime(Calendar.java:1089)
09-27 10:56:03.189 E/ACRA    (16515): 	at sa.com.rae.vzool.kafeh.ui.fragment.form.OwnerFormFragment.hijriDate(OwnerFormFragment.java:624)
09-27 10:56:03.189 E/ACRA    (16515): 	at sa.com.rae.vzool.kafeh.ui.fragment.form.OwnerFormFragment$5.onClick(OwnerFormFragment.java:273)
09-27 10:56:03.189 E/ACRA    (16515): 	at android.view.View.performClick(View.java:5706)
09-27 10:56:03.189 E/ACRA    (16515): 	at android.view.View$PerformClick.run(View.java:22834)
09-27 10:56:03.189 E/ACRA    (16515): 	at android.os.Handler.handleCallback(Handler.java:836)
09-27 10:56:03.189 E/ACRA    (16515): 	at android.os.Handler.dispatchMessage(Handler.java:103)
09-27 10:56:03.189 E/ACRA    (16515): 	at android.os.Looper.loop(Looper.java:203)
09-27 10:56:03.189 E/ACRA    (16515): 	at android.app.ActivityThread.main(ActivityThread.java:6339)
09-27 10:56:03.189 E/ACRA    (16515): 	at java.lang.reflect.Method.invoke(Native Method)
09-27 10:56:03.189 E/ACRA    (16515): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
09-27 10:56:03.189 E/ACRA    (16515): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
```

Thanks

**Comment by alhazmy13** [comment]
I hope this issue fixed with version 2.1.0
