### ISSUE TITLE
com.github.msarhan.ummalqura.calendar.text.UmmalquraFormatData_fr_FR', key 

### ISSUE THREAD

**Issue by lukamodric10** [alhazmy13/HijriDatePicker#31]
hi sur i am getting this error in my log 
com.github.msarhan.ummalqura.calendar.text.UmmalquraFormatData_fr_FR', key 
i followed exactly what you said i don't know why this error keep showing ... 
` Process: com.example.mon.muslim, PID: 3005
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.mon.muslim/com.example.mon.muslim.Map}: java.util.MissingResourceException: Can't find resource for bundle 'com.github.msarhan.ummalqura.calendar.text.UmmalquraFormatData_fr_FR', key ''
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2699)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2773)
        at android.app.ActivityThread.access$900(ActivityThread.java:177)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1434)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5930)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
     Caused by: java.util.MissingResourceException: Can't find resource for bundle 'com.github.msarhan.ummalqura.calendar.text.UmmalquraFormatData_fr_FR', key ''
        at java.util.ResourceBundle.missingResourceException(ResourceBundle.java:238)
        at java.util.ResourceBundle.getBundle(ResourceBundle.java:230)
        at java.util.ResourceBundle.getBundle(ResourceBundle.java:159)
        at com.github.msarhan.ummalqura.calendar.UmmalquraDateFormatSymbols.initializeData(UmmalquraDateFormatSymbols.java:91)
        at com.github.msarhan.ummalqura.calendar.UmmalquraDateFormatSymbols.<init>(UmmalquraDateFormatSymbols.java:66)
        at com.github.msarhan.ummalqura.calendar.UmmalquraCalendar.getDisplayName(UmmalquraCalendar.java:325)
        at net.alhazmy13.hijridatepicker.date.hijri.HijriDatePickerDialog.updateDisplay(HijriDatePickerDialog.java:545)
        at net.alhazmy13.hijridatepicker.date.hijri.HijriDatePickerDialog.onCreateView(HijriDatePickerDialog.java:409)
        at android.app.Fragment.performCreateView(Fragment.java:2112)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:904)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1083)
        at android.app.BackStackRecord.run(BackStackRecord.java:834)
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1468)`

**Comment by alhazmy13** [comment]
This is related to `ummalqura-calendar` library, please raise it as bug in there library
