### ISSUE TITLE
Missing resources

### ISSUE THREAD

**Issue by snasrudeen** [alhazmy13/HijriDatePicker#36]
Hi, 

App getting crash when the device language is other than English or Arabic with ummalqura calendar. I tried to update library version to 2.1.0. Unfortunately its min sdk is 19.

While building app with library version 2.1.0 throws following

uses-sdk:minSdkVersion 17 cannot be smaller than version 19 declared in library [net.alhazmy13.hijridatepicker:library:2.1.0] /Users/nasrudeen/.gradle/caches/transforms-1/files-1.1/library-2.1.0.aar/7e9872f81d3ff49e4969aa6dc6bcc092/AndroidManifest.xml as the library might be using APIs not available in 17
	Suggestion: use a compatible library with a minSdk of at most 17,
		or increase this project's minSdk version to at least 19,
		or use tools:overrideLibrary="net.alhazmy13.hijridatepicker" to force usage (may lead to runtime failures)

//Error

java.util.MissingResourceException: Can't find bundle for base name com.github.msarhan.ummalqura.calendar.text.UmmalquraFormatData, locale es_ES
        at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1558)
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1381)
        at java.util.ResourceBundle.getBundle(ResourceBundle.java:847)
        at com.github.msarhan.ummalqura.calendar.UmmalquraDateFormatSymbols.initializeData(UmmalquraDateFormatSymbols.java:91)
        at com.github.msarhan.ummalqura.calendar.UmmalquraDateFormatSymbols.<init>(UmmalquraDateFormatSymbols.java:66)
        at com.github.msarhan.ummalqura.calendar.UmmalquraCalendar.getDisplayName(UmmalquraCalendar.java:325)
        at net.alhazmy13.hijridatepicker.date.hijri.HijriDatePickerDialog.updateDisplay(HijriDatePickerDialog.java:552)
        at net.alhazmy13.hijridatepicker.date.hijri.HijriDatePickerDialog.onCreateView(HijriDatePickerDialog.java:409)
        at android.app.Fragment.performCreateView(Fragment.java:2508)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1279)
        at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2412)
        at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2191)
        at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2147)
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2048)
        at android.app.FragmentManagerImpl$1.run(FragmentManager.java:719)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6651)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)

Is there any way to use version 2.1.0 with min sdk 17?

Thank you.

**Comment by alhazmy13** [comment]
No, you cannot
Min version is 21
