### ISSUE TITLE
Getting invalid Hijrah day of month :31

### ISSUE THREAD

**Issue by husaynirfan** [alhazmy13/HijriDatePicker#52]
I keep getting this error, which i even tried copying the exact thing in order to identify the problems. Still not works. But with the sample provided, it works flawlessly.

My error is : Invalid Hijrah day of month : 31

Here i provide the stack error.

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.myapplication, PID: 13658
    com.github.msarhan.ummalqura.calendar.DateTimeException: Invalid Hijrah day of month: 31
        at com.github.msarhan.ummalqura.calendar.HijrahChronology.getEpochDay(HijrahChronology.java:255)
        at com.github.msarhan.ummalqura.calendar.HijrahChronology.toGregorian(HijrahChronology.java:697)
        at com.github.msarhan.ummalqura.calendar.UmmalquraCalendar.set(UmmalquraCalendar.java:259)
        at net.alhazmy13.hijridatepicker.date.hijri.HijriDatePickerDialog.getEndDate(HijriDatePickerDialog.java:1028)
        at net.alhazmy13.hijridatepicker.date.hijri.MonthAdapter.getCount(MonthAdapter.java:146)
        at android.widget.ListView.setAdapter(ListView.java:493)
        at net.alhazmy13.hijridatepicker.date.hijri.DayPickerView.refreshAdapter(DayPickerView.java:142)
        at net.alhazmy13.hijridatepicker.date.hijri.DayPickerView.setController(DayPickerView.java:114)
        at net.alhazmy13.hijridatepicker.date.hijri.DayPickerView.<init>(DayPickerView.java:105)
        at net.alhazmy13.hijridatepicker.date.hijri.SimpleDayPickerView.<init>(SimpleDayPickerView.java:32)
        at net.alhazmy13.hijridatepicker.date.hijri.HijriDatePickerDialog.onCreateView(HijriDatePickerDialog.java:340)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by yazeed-mohammad** [comment]
I have same error in this code !

            UmmalquraCalendar now = new UmmalquraCalendar();
            HijriDatePickerDialog dpd = HijriDatePickerDialog.newInstance((view1, year, monthOfYear, dayOfMonth) -> {
            }, now.get(IslamicCalendar.YEAR), now.get(IslamicCalendar.MONTH), now.get(IslamicCalendar.DAY_OF_MONTH));
            dpd.setOnCancelListener(dialog -> dismiss());
            dpd.setMenuVisibility(true);
            dpd.setMinYear(1356);
            dpd.setMaxYear(1500);
            dpd.show(getFragmentManager(), "tag");

do you solved it ?

**Comment by husaynirfan** [comment]
No sir, they say its something with dependencies, however, im using the
2.0.2. I go through the HijriDatePickerDialog.java, i dont know why, maybe
bug, it showed 31, which from the original source on github, it showed 29.
Maybe there was a bug.
I need to try edit the original source, and import the fixed module to
android studio.

If you fixed it let me know. Thank you very much.

**Comment by atifaziz1** [comment]
I am getting the same error .. I am using version 2.0.2. Does anyone help in this issue.?
